apiVersion: apps/v1
kind: Deployment
metadata:
  name: {name}
  labels:
    app: {name}
spec:
  selector:
    matchLabels:
      app: {name}
  template:
    metadata:
      labels:
        app: {name}
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values: [{mysql.name}]
            topologyKey: kubernetes.io/hostname
            # namespaces: ["*"]
      containers:
      - image: {image}
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: {mysql.name}-service:3306
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {mysql.name}-secret
              key: MYSQL_PASSWORD
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: {mysql.name}-secret
              key: MYSQL_USER
        - name: WORDPRESS_DB_NAME
          value: {mysql.database}
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: {name}-hostpath
          mountPath: /var/www/html
        - name: {name}-config-php
          mountPath: /usr/local/etc/php/conf.d/{name}-php.ini
          subPath: {name}-php.ini
        resources:
          requests:
            cpu: {resources.requests.cpu}
            memory: {resources.requests.memory}
          limits:
            cpu: {resources.limits.cpu}
            memory: {resources.limits.memory}
      volumes:
      - name: {name}-hostpath
        hostPath:
          path: {hostpath}
          type: DirectoryOrCreate
      - name: {name}-config-php
        configMap:
          name: {name}-php.ini
      priorityClassName: {priority}
